FROM alpine:latest
MAINTAINER uji
RUN apk update
RUN apk upgrade
RUN apk add --no-cache \
    curl \
    gcc \
    git \
    linux-headers \
    musl-dev\
    neovim \
    python-dev \
    py-pip \
    python3-dev \
    py3-pip && \
    rm -rf /var/cache/apk/*
RUN pip3 install --upgrade pip neovim
RUN git clone https://github.com/uji/dotfiles.git
RUN mkdir ~/.config
RUN cp -r dotfiles/.vim ~/.config/nvim
RUN ln -sf ~/dotfiles/.vimrc ~/.config/nvim/init.vim
ENTRYPOINT ["nvim"]
